#pragma once

#include <GLFW/glfw3.h>

namespace glvx {

enum class Key {
    Unknown = -1,
    A = GLFW_KEY_A,
    B = GLFW_KEY_B,
    C = GLFW_KEY_C,
    D = GLFW_KEY_D,
    E = GLFW_KEY_E,
    F = GLFW_KEY_F,
    G = GLFW_KEY_G,
    H = GLFW_KEY_H,
    I = GLFW_KEY_I,
    J = GLFW_KEY_J,
    K = GLFW_KEY_K,
    L = GLFW_KEY_L,
    M = GLFW_KEY_M,
    N = GLFW_KEY_N,
    O = GLFW_KEY_O,
    P = GLFW_KEY_P,
    Q = GLFW_KEY_Q,
    R = GLFW_KEY_R,
    S = GLFW_KEY_S,
    T = GLFW_KEY_T,
    U = GLFW_KEY_U,
    V = GLFW_KEY_V,
    W = GLFW_KEY_W,
    X = GLFW_KEY_X,
    Y = GLFW_KEY_Y,
    Z = GLFW_KEY_Z,
    Num0 = GLFW_KEY_0,
    Num1 = GLFW_KEY_1,
    Num2 = GLFW_KEY_2,
    Num3 = GLFW_KEY_3,
    Num4 = GLFW_KEY_4,
    Num5 = GLFW_KEY_5,
    Num6 = GLFW_KEY_6,
    Num7 = GLFW_KEY_7,
    Num8 = GLFW_KEY_8,
    Num9 = GLFW_KEY_9,
    Escape = GLFW_KEY_ESCAPE,
    LControl = GLFW_KEY_LEFT_CONTROL,
    LShift = GLFW_KEY_LEFT_SHIFT,
    LAlt = GLFW_KEY_LEFT_ALT,
    LSystem = GLFW_KEY_LEFT_SUPER,
    RControl = GLFW_KEY_RIGHT_CONTROL,
    RShift = GLFW_KEY_RIGHT_SHIFT,
    RAlt = GLFW_KEY_RIGHT_ALT,
    RSystem = GLFW_KEY_RIGHT_SUPER,
    Menu = GLFW_KEY_MENU,
    LBracket = GLFW_KEY_LEFT_BRACKET,
    RBracket = GLFW_KEY_RIGHT_BRACKET,
    Semicolon = GLFW_KEY_SEMICOLON,
    Comma = GLFW_KEY_COMMA,
    Period = GLFW_KEY_PERIOD,
    Apostrophe = GLFW_KEY_APOSTROPHE,
    Slash = GLFW_KEY_SLASH,
    Backslash = GLFW_KEY_BACKSLASH,
    Minus = GLFW_KEY_MINUS,
    Plus = GLFW_KEY_EQUAL,
    Enter = GLFW_KEY_ENTER,
    Space = GLFW_KEY_SPACE,
    Tab = GLFW_KEY_TAB,
    Backspace = GLFW_KEY_BACKSPACE,
    Insert = GLFW_KEY_INSERT,
    Delete = GLFW_KEY_DELETE,
    End = GLFW_KEY_END,
    Home = GLFW_KEY_HOME,
    PageUp = GLFW_KEY_PAGE_UP,
    PageDown = GLFW_KEY_PAGE_DOWN,
    Up = GLFW_KEY_UP,
    Left = GLFW_KEY_LEFT,
    Down = GLFW_KEY_DOWN,
    Right = GLFW_KEY_RIGHT,
    Pause = GLFW_KEY_PAUSE,
    F1 = GLFW_KEY_F1,
    F2 = GLFW_KEY_F2,
    F3 = GLFW_KEY_F3,
    F4 = GLFW_KEY_F4,
    F5 = GLFW_KEY_F5,
    F6 = GLFW_KEY_F6,
    F7 = GLFW_KEY_F7,
    F8 = GLFW_KEY_F8,
    F9 = GLFW_KEY_F9,
    F10 = GLFW_KEY_F10,
    F11 = GLFW_KEY_F11,
    F12 = GLFW_KEY_F12,
    F13 = GLFW_KEY_F13,
    F14 = GLFW_KEY_F14,
    F15 = GLFW_KEY_F15,
    F16 = GLFW_KEY_F16,
    F17 = GLFW_KEY_F17,
    F18 = GLFW_KEY_F18,
    F19 = GLFW_KEY_F19,
    F20 = GLFW_KEY_F20,
    F21 = GLFW_KEY_F21,
    F22 = GLFW_KEY_F22,
    F23 = GLFW_KEY_F23,
    F24 = GLFW_KEY_F24,
    CapsLock = GLFW_KEY_CAPS_LOCK,
    ScrollLock = GLFW_KEY_SCROLL_LOCK,
    NumLock = GLFW_KEY_NUM_LOCK,
    PrintScreen = GLFW_KEY_PRINT_SCREEN,
    PauseBreak = GLFW_KEY_PAUSE,
    LeftCurlyBracket = GLFW_KEY_LEFT_BRACKET,
    RightCurlyBracket = GLFW_KEY_RIGHT_BRACKET,
    Grave = GLFW_KEY_GRAVE_ACCENT,
    NumMultiply = GLFW_KEY_KP_MULTIPLY,
    NumAdd = GLFW_KEY_KP_ADD,
    NumSeparator = 337,
    NumSubtract = GLFW_KEY_KP_SUBTRACT,
    NumDecimal = GLFW_KEY_KP_DECIMAL,
    NumDivide = GLFW_KEY_KP_DIVIDE,
    Num0_ = GLFW_KEY_KP_0,
    Num1_ = GLFW_KEY_KP_1,
    Num2_ = GLFW_KEY_KP_2,
    Num3_ = GLFW_KEY_KP_3,
    Num4_ = GLFW_KEY_KP_4,
    Num5_ = GLFW_KEY_KP_5,
    Num6_ = GLFW_KEY_KP_6,
    Num7_ = GLFW_KEY_KP_7,
    Num8_ = GLFW_KEY_KP_8,
    Num9_ = GLFW_KEY_KP_9,
    Numpad0 = GLFW_KEY_KP_0,
    Numpad1 = GLFW_KEY_KP_1,
    Numpad2 = GLFW_KEY_KP_2,
    Numpad3 = GLFW_KEY_KP_3,
    Numpad4 = GLFW_KEY_KP_4,
    Numpad5 = GLFW_KEY_KP_5,
    Numpad6 = GLFW_KEY_KP_6,
    Numpad7 = GLFW_KEY_KP_7,
    Numpad8 = GLFW_KEY_KP_8,
    Numpad9 = GLFW_KEY_KP_9,
};

enum class Modifier {
    None = 0,
    Control = 1,
    Shift = 2,
    Alt = 4,
    System = 8
};

inline Modifier glfwToModifier(int glfw_mods) {
    Modifier result = Modifier::None;
    if (glfw_mods & GLFW_MOD_CONTROL) result = static_cast<Modifier>(static_cast<int>(result) | static_cast<int>(Modifier::Control));
    if (glfw_mods & GLFW_MOD_SHIFT) result = static_cast<Modifier>(static_cast<int>(result) | static_cast<int>(Modifier::Shift));
    if (glfw_mods & GLFW_MOD_ALT) result = static_cast<Modifier>(static_cast<int>(result) | static_cast<int>(Modifier::Alt));
    if (glfw_mods & GLFW_MOD_SUPER) result = static_cast<Modifier>(static_cast<int>(result) | static_cast<int>(Modifier::System));
    return result;
}

}
